# Generated by Django 5.2.5 on 2025-11-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_profile_e_wallet_profile_license_plate_parkingrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_image', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang đỗ'), ('COMPLETED', 'Đã hoàn thành')], default='ACTIVE', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Thời gian đỗ (phút)', null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí đỗ xe', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['license_plate', 'status'], name='parking_par_license_ada01f_idx'), models.Index(fields=['-entry_time'], name='parking_par_entry_t_1d4168_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=20)),
                ('confidence', models.FloatField(help_text='Độ tin cậy nhận dạng (0-1)')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera_source', models.CharField(default='raspberrypi_cam', max_length=50)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Xe vào'), ('EXIT', 'Xe ra'), ('DETECTION', 'Phát hiện thường')], default='DETECTION', max_length=20)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['license_plate', '-detected_at'], name='parking_veh_license_048a71_idx'), models.Index(fields=['event_type', '-detected_at'], name='parking_veh_event_t_e6eebc_idx')],
            },
        ),
    ]
