# Generated by Django 5.2.7 on 2025-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingsession_vehicledetection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicledetection',
            name='parking_veh_license_048a71_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicledetection',
            name='parking_veh_event_t_e6eebc_idx',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='event_type',
            field=models.CharField(choices=[('ENTRY', 'Vào bãi'), ('EXIT', 'Ra bãi')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='vehicledetection',
            index=models.Index(fields=['-detected_at', 'license_plate'], name='parking_veh_detecte_4e0a69_idx'),
        ),
    ]
