# Generated by Django 5.2.7 on 2025-11-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_vehicledetection_parking_veh_license_048a71_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
