# Generated by Django 5.2.7 on 2025-11-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ParkingRecord',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
