# Generated by Django 5.2.7 on 2025-11-17 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_remove_profile_user_remove_transaction_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingsession',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Giao dịch đỗ xe', 'verbose_name_plural': 'Giao dịch đỗ xe'},
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán'), ('FREE', 'Miễn phí')], default='UNPAID', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời lượng đỗ (phút)'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh lúc vào'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_time',
            field=models.DateTimeField(db_index=True, verbose_name='Thời điểm vào'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='exit_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh lúc ra'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm ra'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Số tiền phải trả'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang đỗ'), ('COMPLETED', 'Đã hoàn thành')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['payment_status'], name='parking_par_payment_62cc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['created_at'], name='parking_par_created_2acef5_idx'),
        ),
    ]
